# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/globalspace/jiveplus/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/globalspace/jiveplus/overlay

$(call inherit-product, vendor/globalspace/jiveplus/jiveplus-vendor-blobs.mk)

# Prebuilt APKs
PRODUCT_PACKAGES += \
    com.qualcomm.location \
    qcrilmsgtunnel \
    shutdownlistener \
    TimeService \
#    btmultisim \
    Evt \
    fastdormancy \
    GosoSystemService \
    MdnForImsi \
    NetworkSetting 

# Prebuilt jars
PRODUCT_PACKAGES += \
    cneapiclient \
    com.quicinc.cne \
    qmapbridge \
    com.qualcomm.location.vzw_library \
    qcnvitems \
    qcrilhook \
#    oem-services \
    phoneclient \
    services-ext \
    org.codeaurora.Performance \
    vcard2 \
    btmultisimlibrary \
    imslibrary

# Prebuilt vendor/libs needed for compilation
PRODUCT_PACKAGES += \
    libtime_genoff
